[project]
name = "flipkart-mobile-phone-data-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "curl-cffi>=0.13.0",
    "pandas>=2.3.3",
    "requests>=2.32.5",
]
